Repository redhat-developer/devconsole-git, pull requests merged in 2019-04, with the labels that each got.

#13 fix: sort languages correctly-by numbers not strings
  pkg/git/langs.go
  pkg/git/langs_test.go
Labels: approved, ok-to-test, ¯\_(ツ)_/¯

#16 Adds details in README
  README.md
Labels: approved

#19 feat(ODC-469): when secret is not provided then default credentials are used
  pkg/git/detector/detector.go
  pkg/git/detector/detector_whitebox_test.go
  pkg/git/repository/bitbucket/service.go
  pkg/git/repository/bitbucket/service_test.go
  pkg/git/repository/generic/service.go
  pkg/git/repository/generic/service_test.go
  pkg/git/repository/github/service.go
  pkg/git/repository/github/service_test.go
  pkg/git/repository/gitlab/service.go
  pkg/git/repository/gitlab/service_test.go
  pkg/git/repository/service.go
  pkg/git/secret.go
  pkg/git/secret_test.go
  pkg/test/service.go
Labels: approved

#20 chore: use BuildEnvStats and types from devconsole-api
  Gopkg.lock
  make/test.mk
  pkg/git/detector/detector.go
  pkg/git/detector/detector_whitebox_test.go
  pkg/git/detector/environment.go
  pkg/git/detector/environment_whitebox_test.go
Labels: approved

#21 feat(ODC-540): when API rate limit is reached then don't use API calls for build type detection
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller_test.go
  pkg/git/detector/build/tool.go
  pkg/git/detector/detector.go
  pkg/git/detector/detector_tool_whitebox_test.go
  pkg/git/detector/detector_whitebox_test.go
  pkg/git/detector/environment.go
  pkg/git/detector/environment_whitebox_test.go
  pkg/git/repository/bitbucket/service.go
  pkg/git/repository/bitbucket/service_test.go
  pkg/git/repository/checker.go
  pkg/git/repository/generic/service.go
  pkg/git/repository/generic/service_test.go
  pkg/git/repository/github/service.go
  pkg/git/repository/github/service_test.go
  pkg/git/repository/gitlab/service.go
  pkg/git/repository/gitlab/service_test.go
  pkg/git/repository/service.go
  pkg/git/repository/service_test.go
  pkg/log/log.go
  pkg/test/gock.go
  pkg/test/service.go
Labels: size/XXL

#22 Rename git-service to devconsole-git
  Dockerfile.deploy
  Dockerfile.deploy.rhel
  Dockerfile.dev
  Makefile
  README.md
  cmd/manager/main.go
  make/Makefile.dev
  minishift/README.md
  pkg/controller/add_gitsourceanalysis.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller_test.go
  pkg/git/detector/detector.go
  pkg/git/detector/detector_tool_whitebox_test.go
  pkg/git/detector/detector_whitebox_test.go
  pkg/git/langs_test.go
  pkg/git/repository/bitbucket/service.go
  pkg/git/repository/bitbucket/service_test.go
  pkg/git/repository/checker.go
  pkg/git/repository/generic/service.go
  pkg/git/repository/generic/service_test.go
  pkg/git/repository/github/service.go
  pkg/git/repository/github/service_test.go
  pkg/git/repository/gitlab/service.go
  pkg/git/repository/gitlab/service_test.go
  pkg/git/repository/identifier_test.go
  pkg/git/repository/service.go
  pkg/git/repository/service_test.go
  pkg/git/secret_test.go
  pkg/test/git.go
  pkg/test/service.go
Labels: size/L

#24 chore: remove generic git from detector
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller_test.go
  pkg/git/detector/detector.go
  pkg/git/detector/detector_whitebox_test.go
Labels: size/M

#23 feat(ODC-451): add function that checks if repo is reachable and branch exists
  Gopkg.lock
  pkg/git/connection/error.go
  pkg/git/connection/validator.go
  pkg/git/connection/validator_test.go
Labels: size/L

#26 feat(ODC-64): add credentials,repository and branch validation
  pkg/git/connection/validator.go
  pkg/git/connection/validator_test.go
  pkg/git/connection/validator_whitebox_test.go
  pkg/git/repository/bitbucket/service.go
  pkg/git/repository/bitbucket/service_test.go
  pkg/git/repository/generic/service.go
  pkg/git/repository/generic/service_test.go
  pkg/git/repository/github/service.go
  pkg/git/repository/github/service_test.go
  pkg/git/repository/gitlab/service.go
  pkg/git/repository/gitlab/service_test.go
  pkg/git/repository/service.go
  pkg/git/secret.go
  pkg/test/git.go
  pkg/test/gock.go
  pkg/test/service.go
Labels: size/XL

#27 chore(ODC-611): move controllers from devconsole-operator
  pkg/controller/add_gitsource.go
  pkg/controller/gitsource/gitsource_controller.go
  pkg/controller/gitsource/gitsource_controller_test.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller_test.go
Labels: size/L

#28 feat(ODC-64): modify GS controller to validate credentials,repository and branch
  pkg/controller/gitsource/gitsource_controller.go
  pkg/controller/gitsource/gitsource_controller_test.go
Labels: size/L

#29 add local make target & fix deployment
  README.md
  deploy/namespace.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  make/Makefile.dev
Labels: size/M

#30 feat: add failure reason to status when analysis fails
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller_test.go
  pkg/git/detector/detector.go
  pkg/git/detector/detector_whitebox_test.go
Labels: size/L

#31 fix: validate correctly URL ending with slash
  pkg/git/connection/validator.go
  pkg/git/connection/validator_test.go
Labels: size/S

#32 fix: use custom error properly (via interface)
  pkg/controller/gitsource/gitsource_controller.go
  pkg/git/connection/error.go
  pkg/git/connection/validator.go
  pkg/git/connection/validator_test.go
  pkg/git/connection/validator_whitebox_test.go
Labels: size/M
